### ISSUE TITLE
checkBitField, fs.existsSync(syml), syml

### ISSUE THREAD

**Issue by ghost** [Vance-ng-vn/Stremio-Seeds#1]
`false C:\Users\\AppData\Roaming\stremio\stremio-server\stremio-cache\29dc498a9f0209a059afb62561713124c7f87005\Pulp Fiction - Tempo de Violência 20 Anos 1080p (1994 - 2014) Dual Áudio BluRay 5.1 -- By - Lucas Firmo\Pulp Fiction - Tempo de Violência 20 Anos 1080p (1994 - 2014) Dual Áudio BluRay 5.1 -- By - Lucas Firmo.srt
Unknow Error! Error: EPERM: operation not permitted, symlink 'C:\Users\\AppData\Roaming\stremio\stremio-server\stremio-cache\29dc498a9f0209a059afb62561713124c7f87005\0' -> 'C:\Users\\AppData\Roaming\stremio\stremio-server\stremio-cache\29dc498a9f0209a059afb62561713124c7f87005\Pulp Fiction - Tempo de Violência 20 Anos 1080p (1994 - 2014) Dual Áudio BluRay 5.1 -- By - Lucas Firmo\Pulp Fiction - Tempo de Violência 20 Anos 1080p (1994 - 2014) Dual Áudio BluRay 5.1 -- By - Lucas Firmo.srt'
    at Object.symlinkSync (node:fs:1813:11)
    at addTorrent (C:\Users\\AppData\Local\Programs\LNV\Stremio-4\index.js:288:20)
    at Update (C:\Users\\AppData\Local\Programs\LNV\Stremio-4\index.js:150:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Timeout._onTimeout (C:\Users\\AppData\Local\Programs\LNV\Stremio-4\index.js:107:17)`

Yes, I'm running it locally. I didn't build.

Not adding a single torrent at all to qBitTorrent.

Another issue also:
`const WINDOWS_DEFAULT_CACHE_DIR = path.join(os.homedir(), '/AppData/Roaming/stremio/stremio-server/'); // Fix`

Looking forward!

**Comment by Vance-ng-vn** [comment]
Windows requires administrator privileges to create a symbolic link, you can try running Stremio with administrator.
